### ISSUE TITLE
Grab IoError - Interrupted Syscall on Wayland

### ISSUE THREAD

**Issue by bournedrewd** [jersou/mouse-actions#5] opened 2023-06-10 23:42 UTC
Hi, thanks for developing this. The ability to have a program like EasyStroke for Wayland is invaluable when it comes to setting up a heavily touchscreen-driven, yet minimal setup.
Unfortunately, the program (latest AppImage) does not work for me under wayland (sway wm specifically).

After having setup the requirements and a simple stroke command within the GUI, I call
`mouse-actions-gui --no-listen start`

This does indeed start mouse-actions and upon entering my stroke it is correctly detected:
```
[2023-06-10T22:58:44Z INFO mouse_actions::process_event]       -> cmd ["bash', '-c', 'htop"]
```

However it then throws an error:
```
[2023-06-10T22:58:46Z ERROR mouse_actions::process_args]  Grab Error: IoError(
    Os {
        code: 4,
        kind: Interrupted,
        message: "Interrupted system call",
        },
    )
```
And ultimately whatever command I set is not executed.

**Comment by pallaswept** [comment] 2023-06-14 04:01
I mentioned this experience over in #3, the problem is that when the GUI exits and starts the daemon, the `--no-listen` argument isn't used, so you get the usual error when running without it. You can deal with it by manually starting the daemon with the `--no-listen` argument, it'll use the config you successfully created in the GUI and work just fine.

The plan for the future is to automatically detect the wayland session and configure the app accordingly so the need for the argument will go away and it'll work just fine. Either @jersou or myself will definitely take care of it one day, but until then now you have a workaround I hope that will help.

**Comment by jersou** [comment] 2023-06-18 07:13
Hi, I have just released the v0.4.2 that had "Wayland detection" (check if the "WAYLAND_DISPLAY" env var exists).

The "--no-listen" option is no longer necessary with Wayland.
Furthermore, the bug "the GUI doesn't fowrward the --no-listen argument" is also fixed (the bug described by @pallaswept).

@bournedrewd can you check the v0.4.2 ?

**Comment by pallaswept** [comment] 2023-06-21 10:22
> Hi, I have just released the v0.4.2 that had "Wayland detection" (check if the "WAYLAND_DISPLAY" env var exists).
> 
> The "--no-listen" option is no longer necessary with Wayland. Furthermore, the bug "the GUI doesn't fowrward the --no-listen argument" is also fixed (the bug described by @pallaswept).
> 
> @bournedrewd can you check the v0.4.2 ?

Working very well here, thanks for that!

**Comment by bournedrewd** [comment] 2023-06-25 15:31
> Hi, I have just released the v0.4.2 that had "Wayland detection" (check if the "WAYLAND_DISPLAY" env var exists).
> 
> The "--no-listen" option is no longer necessary with Wayland. Furthermore, the bug "the GUI doesn't fowrward the --no-listen argument" is also fixed (the bug described by @pallaswept).
> 
> @bournedrewd can you check the v0.4.2 ?

The `--no-listen` was not really the issue for me, but I can confirm that mouse-actions now correctly picks it up on wayland.

It seems like my issue (the `IoError`) has nothing to do directly with mouse-actions but more so the command I input. I was able to run commands in my PATH just fine, however, any direct shell scripting seems to trigger the IoError for me.
I.e.:
`sh <command>`
`echo 'test' >> /tmp/test`
`bash -c <command>`

**Comment by pallaswept** [comment] 2023-06-26 18:55
> `bash -c <command>` all throw the error I originally described.

This is literally the only thing I do with mouse-actions thus far (to call ydotool and send keystrokes). It's picky about the formatting, though. I gave an example [over here](https://github.com/jersou/mouse-actions/issues/7#issuecomment-1600618901) hopefully it will be helpful?

**Comment by bournedrewd** [comment] 2023-06-26 19:28
> > `bash -c <command>` all throw the error I originally described.
> 
> This is literally the only thing I do with mouse-actions thus far (to call ydotool and send keystrokes). It's picky about the formatting, though. I gave an example [over here](https://github.com/jersou/mouse-actions/issues/7#issuecomment-1600618901) hopefully it will be helpful?
> 
> A screengrab to show what I mean ![image](https://user-images.githubusercontent.com/132128962/248906894-974e4688-5b00-49f1-bf2a-8861ac0b2c2d.png)

It seems like I was not able to actually add new elements to the JSON array within the GUI as the input field simply wouldn't allow to add any `"` or add a `,` after the first element.
Manually editing the conf file with an external editor, however, did fix the issue and I can successfully execute any command this way. Thank you!

I suppose that solves this issue particular issue.

**Comment by pallaswept** [comment] 2023-06-28 00:26
> It seems like I was not able to actually add new elements to the JSON array within the GUI as the input field simply wouldn't allow to add any `"` or add a `,` after the first element.

I came across this, too. Sometimes it lets me type them and sometimes it doesn't, I'm not exactly sure of the exact conditions here it works and doesn't. Frankly I reached the point where I would generate the string, formatting and all, in a text editor or a shell prompt or anywhere else I could type, then cut-and-paste it into the GUI - that is, when I was using the GUI. I've been using this since even before it was very first released and the GUI has and used to have other issues that made me usually only utilise it to draw the gesture and I did the rest in the config file in a text editor. It's early days for this app, but you can be confident that these little bumps will be ironed out in time.

**Comment by jersou** [comment] 2023-06-28 05:57
I'm reopening this ticket, and I understand why this happens: currently, this field must always be a valid json, which is why it prevents intermediate entries.
it's obviously not a good idea, and I need to change this behavior.

In the TODO section of the README, there is `use https://crates.io/crates/deno_task_shell to execute commands ?`, I'll see if it's not the right time to do it...

**Comment by jersou** [comment] 2023-06-28 06:06
ok, this last bug is a duplicate of #7, I close the current and move my comment to #7

**Closed by jersou** 2023-06-28 06:06 UTC
